// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsX42FCD6nxPv_Y6Xpj7upRHN6DyL9Y3g',
    appId: '1:11138466879:web:4e48cbfd8a983a9277648a',
    messagingSenderId: '11138466879',
    projectId: 'sketch-games',
    authDomain: 'sketch-games.firebaseapp.com',
    storageBucket: 'sketch-games.appspot.com',
    measurementId: 'G-0M4N9V5JR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWhBSt-SS2bZV_YRcVQqGSXYbnUq83ORw',
    appId: '1:11138466879:android:ddf43195468aee1577648a',
    messagingSenderId: '11138466879',
    projectId: 'sketch-games',
    storageBucket: 'sketch-games.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClP18aYkBPwhCcXu8JOg0gwJUnBVzSuyk',
    appId: '1:11138466879:ios:d0c7b7354f426ba277648a',
    messagingSenderId: '11138466879',
    projectId: 'sketch-games',
    storageBucket: 'sketch-games.appspot.com',
    iosClientId: '11138466879-lll2286k3neaddeirfnhfhji4cia3fv0.apps.googleusercontent.com',
    iosBundleId: 'com.roseikteam1.sketchgames.sketchGames',
  );
}
